### ISSUE TITLE
Prevent the full loading of content of HTTP POST requests into the RAM

### ISSUE THREAD

**Issue by hozblok** [django/daphne#253] opened 2019-03-18 17:38 UTC
Please, can anyone say how to avoid the following behavior?

For example, we send a large HTTP POST request with multipart/form-data (~2 Gb) using channels, daphne, `AsgiHandler` and `AsgiRequest`. (let's say we chose the wrong file to upload).

settings.py contains `DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 25` and `FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 5` settings.

[Here](https://github.com/django/channels/blob/a1ecd5ee72a538f19bdd9e8f6bb91bb8aabba5d9/channels/http.py#L127) in `AsgiRequest` we raise `RequestDataTooBig` exception.

So the response is `HttpResponse("413 Payload too large", status=413)` [(here)](https://github.com/django/channels/blob/a1ecd5ee72a538f19bdd9e8f6bb91bb8aabba5d9/channels/http.py#L244). Ok.

But before all this: [here](https://github.com/django/daphne/blob/67cfa98b0016abee66fe1d90c7db3ea1ea1d001f/daphne/http_protocol.py#L188) we load two gigabytes of unwanted data into RAM... ?

Perhaps is there a way to check the `content-length` in the  `__init__` method of `AsgiHandler`?  How to prevent uploads to RAM correctly?

**Comment by JohnDoee** [comment] 2019-03-18 18:08
I think this would be a dupe of #126.

Check out [uvicorn](https://github.com/encode/uvicorn), I'm pretty sure it'll handle large requests a lot better.

**Comment by carltongibson** [comment] 2019-03-18 20:00
Yep. This is a duplicate. It'll come but not available yet.

**Closed by carltongibson** 2019-03-18 20:00 UTC
