### ISSUE TITLE
No response sent upstream to websocket client, ping timeout

### ISSUE THREAD

**Issue by robdoesstuff** [django/daphne#113] opened 2017-05-09 18:59 UTC
Hi,

I'm using nginx as a reverse proxy and running daphne bound to localhost:8001 using asgi redis as backend with 2 workers running and am seeing the following logs from daphne:
```
127.0.0.1:38006 - - [09/May/2017:18:52:37] "WSCONNECTING /wsapi/v1" - -
DEBUG Upgraded connection daphne.response.RGQewZnEoT!wLuySyWzLr to WebSocket daphne.response.RGQewZnEoT!ygHuTTKMxL
DEBUG WebSocket daphne.response.RGQewZnEoT!ygHuTTKMxL open and established
127.0.0.1:38006 - - [09/May/2017:18:52:37] "WSCONNECT /wsapi/v1" - -
DEBUG WebSocket daphne.response.RGQewZnEoT!ygHuTTKMxL accepted by application
WARNING dropping connection to peer tcp4:127.0.0.1:38006 with abort=True: WebSocket ping timeout (peer did not respond with pong in time)
DEBUG WebSocket closed for daphne.response.RGQewZnEoT!ygHuTTKMxL
```

My channel worker is getting the initial connect message and is sending back Accept: true to the reply channel, but the websocket client (in chrome for testing) does not appear to see that the connection was accepted. This code all works correctly when run in a dev environment using startserver.

My nginx config looks like this:
```
    # Websocket API proxy to daphne
    location /wsapi {
        proxy_pass http://daphne;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
```

```
    # Finally, send all non-media requests to the Django server.
    location / {
        uwsgi_pass  django;
        include     /usr/src/app/django/uwsgi_params;
    }
```

Any ideas of how to continue debugging? I've tried a number of configuration tweaks that I've seen others make but nothing seems to be helping.

**Comment by andrewgodwin** [comment] 2017-05-09 19:40
What channel layer are you using? And does Daphne serve normal HTTP requests OK?

**Comment by robdoesstuff** [comment] 2017-05-09 20:51
I'm running daphne with `daphne -b 0.0.0.0 -p 8001 -v 2 <myapp>.asgi:channel_layer`

Where <myapp>/asgi.py is:

```
import os
from channels.asgi import get_channel_layer

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "<myapp>.settings")

channel_layer = get_channel_layer()```

Where in all above code, <myapp> is the actual app module, not literally <myapp> :)

Running http requests through nginx through daphne does work. It just seems that there is no websocket upstream data passed back to the client in this configuration. I just see a pending WS request in chrome that eventually gets back a 101 but only after the ping timeout/disconnect, but then it's disconnected.

When I directly run daphne and a worker without nginx and connect to it, I have no issues. It works locally like that. The websocket receives a 101 and I see several frames of communication on the client-side.

**Comment by andrewgodwin** [comment] 2017-05-09 20:56
Hm, what your describing sounds like nginx is doing something wrong - if you're able to talk directly to Daphne and everything works, then it's not a daphne problem per se. Is there any lines in the nginx logs that might point to it dropping or interfering with the connection?

**Comment by robdoesstuff** [comment] 2017-05-09 21:09
Right now I'm in agreement with you. I think nginx is not sending the initial 101 response back. I don't know the websocket protocol well enough to debug it in better detail yet, though these types of problems have a tendency to educate a person in greater detail than they cared to have. 

One takeaway would be that it would be great if there was a doc with channels for using with nginx, haproxy, etc which gave people a working starting point. I've found several things on github and stackoverflow on the topic but it doesn't appear to be working for me yet.

I'll keep digging. Thanks for your help.

**Comment by andrewgodwin** [comment] 2017-05-09 21:11
The problem is that there's so much stuff that can go wrong because of the way WebSockets uses HTTP/1.1 upgrade which so much old stuff doesn't support. It might be nginx, it might be a CDN in front of it, it might be a local proxy - your nginx config looks pretty reasonable (you have all the right headers and stuff). Did you expose Daphne on the same port as nginx and behind any similar caches/CDNs in front, or did you do it on a side port?

Also, I'm going to close this, as it's not a Daphne bug.

**Closed by andrewgodwin** 2017-05-09 21:11 UTC
Labels: blocked/user-response

**Comment by robdoesstuff** [comment] 2017-05-09 22:15
The problem? I was building in a docker container which only supported up to Nginx 1.2... nginx didn't add support for WS until 1.3. I upgraded and everything works as expected. Thanks for your help!

**Comment by tveritinova** [comment] 2017-07-16 21:42
@robdoesstuff I have the same problem, but I don't use docker, what I need to upgrade?

**Comment by proofit404** [comment] 2017-07-18 11:56
@tveritinova Do you use nginx setup? If you send requests directly to the Daphne instance, does it works porperly?
