### ISSUE TITLE
daphne doesn't close websocket 

### ISSUE THREAD

**Issue by Necrobsd** [django/daphne#200] opened 2018-05-20 09:46 UTC
Hello! I use Daphne 2 and Channels 2 on my backend behind Nginx. 
I want to disconnect websockets if clients connection is broken.
Nginx config:
```
server {
    listen 80;
    location / {
                proxy_pass http://unix:/home/myproject/daphne.sock;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_redirect     off;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
    }
}
```
Daphne runs with command: 
`daphne --ping-interval 2 --ping-timeout 10 -u /home/myproject/daphne.sock  myproject.asgi:application`

Using a browser, I connect to the websocket, receive some messages, then I close browser, but websocket is still running and doesnt close even after 10 seconds.
What Im doing wrong?

**Comment by andrewgodwin** [comment] 2018-05-20 16:49
How are you determining that the websocket is still running? This works as expected when I tested it just now, so I'd be curious what you're looking at and additionally if this still happens if you connect to Daphne directly (it might be Nginx holding it open)

**Comment by Necrobsd** [comment] 2018-05-21 00:31
Well, my WebsocketConsumer sends requests to the servers, and prints each request and response to the console. And when I close my browser, it still continues printing requests to the console until the end of the script.
I disabled nginx proxy, and connect to daphne directly, repeate experiment and took the same results. Websocket still printing requests data to console.

**Comment by andrewgodwin** [comment] 2018-05-21 00:58
Do you just spin up an infinite loop or coroutine to do that? If you do, you are responsible for closing out the loop/coroutine when your socket disconnects (override the disconnect method), as otherwise it'll run even without a socket.

**Comment by Necrobsd** [comment] 2018-05-21 02:46
Yes, my WebsocketConsumer has While loop, and I have no ideas how to stop it when websocket disconnected

**Comment by andrewgodwin** [comment] 2018-05-21 02:52
If you post it here I can help suggest how to close it on disconnect. I will close the ticket, though, as this is not a bug in Daphne.

**Closed by andrewgodwin** 2018-05-21 02:52 UTC
Labels: blocked/user-response

**Comment by andrewgodwin** [comment] 2018-05-22 09:02
Two suggested options:

- Write to a variable on `self` when the socket closes (e.g. `self.closed`) and check for that in your loop. If it's set, abort the loop.

- Launch your code as a second coroutine (using loop.create_task from asyncio) and then cancel that task when the socket is disconnected.
