### ISSUE TITLE
Random 502 connection error

### ISSUE THREAD

**Issue by muhammedabad** [django/daphne#142] opened 2017-10-27 10:24 UTC
daphne==1.3.0
Django==1.11.6
asgi-redis==1.4.3
channels==1.1.8

Python version: 3.6.1
Process manager: supervisor

I'm not sure when this actually started as the project is currently on a staging environment, but it was working about 3 weeks ago.

Every now and then the websocket connection fails with a 502 error, but it seems to connect successfully more often than not. I do understand that the issue might be on my server config, but I just want to paste the info I have and see if anyone can spot a possible problem.

The front end is a SPA with a backend API using django rest framework. The ws connection is initialized when a user logs in and is disconnected on logout. 

Note: I've used placeholders to indicate my project path and domain names.

Sample from the daphne log:

```
2017-10-27 11:39:47,960 INFO     HTTPFactory starting on '/<path_to_project>/daphne.sock'
2017-10-27 11:39:47,961 INFO     Starting factory <daphne.http_protocol.HTTPFactory object at 0x7fdd560e7d68>
2017-10-27 11:40:34,121 DEBUG    Upgraded connection daphne.response.mKpJCStiyd!woVBfLizbj to WebSocket daphne.response.mKpJCStiyd!CvfKoefXIQ
2017-10-27 11:40:34,178 DEBUG    WebSocket daphne.response.mKpJCStiyd!CvfKoefXIQ open and established
2017-10-27 11:40:34,181 DEBUG    WebSocket daphne.response.mKpJCStiyd!CvfKoefXIQ accepted by application
2017-10-27 11:40:43,599 DEBUG    WebSocket closed for daphne.response.mKpJCStiyd!CvfKoefXIQ
2017-10-27 11:41:48,723 DEBUG    Upgraded connection daphne.response.mKpJCStiyd!fdyaDyLRnX to WebSocket daphne.response.mKpJCStiyd!XrOSCMdDpt
2017-10-27 11:41:53,001 WARNING  dropping connection to peer unix:None with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)
2017-10-27 11:41:53,002 DEBUG    WebSocket closed for daphne.response.mKpJCStiyd!XrOSCMdDpt
2017-10-27 11:42:27,637 DEBUG    Upgraded connection daphne.response.mKpJCStiyd!aeHYZdcjEX to WebSocket daphne.response.mKpJCStiyd!fUUanbivFh
2017-10-27 11:42:27,919 DEBUG    WebSocket daphne.response.mKpJCStiyd!fUUanbivFh open and established
2017-10-27 11:42:27,920 DEBUG    WebSocket daphne.response.mKpJCStiyd!fUUanbivFh accepted by application
```

I implemented a retry which works most of the time in the event of connection failure, but am still puzzled why it fails in the first place.

```
# -- Channels Details
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "ROUTING": "myapp.settings.channels.channel_routing",
    },
}
```

The connect consumer:

```
@channel_session_user_from_http
def ws_connect(message, user_id):
    # Add to the WS client group
    if str(message.user.id) != str(user_id):
        # Block a user from connecting to another user's channel by terminating the connection.
        message.reply_channel.send({"close": True})

    message.channel_session['room'] = user_id

    Group(user_id).add(message.reply_channel)

    # Accept the connection
    message.reply_channel.send({"accept": True})
```

nginx conf extract below:

```
upstream daphne-myapp {
    server unix:/<path_to_project>/daphne.sock;
}

server {
    # the port your site will be served on
    listen 443 ssl;


  # Send all websocket requests to Daphne.
  location /ws/ {
      proxy_pass http://daphne-myapp;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
}
```

Supervisor conf:
```
[program:myapp_daphne_server]
command=/usr/local/bin/myapp-daphne-server.sh
autostart=true
autorestart=true
stdout_logfile=/var/log/myapp-daphne.log
```

the contents of the script (myapp-daphne-server.sh):

```
source /<path_to_env>/bin/activate
cd myapp/myapp
exec daphne myapp.asgi:channel_layer -e ssl:443:privateKey=/<path_to_.key>:certKey=<path_to.pem> --unix-socket=<path_to_project>/daphne.sock -v 2
```

The worker is also configured with supervisor in a similar manner, with the command in the shell script simply being `python manage.py runworker`

An nginx error log sample:

```
2017/10/27 09:43:48 [error] 529#0: *803 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.21, server: myapp.com, request: "GET /ws/8e9278f5-7f03-4c47-9489-53d65ef43fab/?session_key=w7q4kgkkhwt53uhrdz9dysedplpkdx87 HTTP/1.1", upstream: "http://unix:/.<path_to_project>/daphne.sock:/ws/8e9278f5-7f03-4c47-9489-53d65ef43fab/?session_key=w7q4kgkkhwt53uhrdz9dysedplpkdx87", host: "myapp.com"
```

a sample websocket connection URL looks like this:

```
wss://myapp.com/ws/8e9278f5-7f03-4c47-9489-53d65ef43fab/?session_key=w7q4kgkkhwt53uhrdz9dysedplpkdx87
```
I've spent some time ensuring that the configs are correct. I did notice something in the docs about using process managers.

```
If daphne is being run inside a process manager such as Circus you might want it to bind to a file descriptor passed down from a parent process. To achieve this you can use the --fd flag:

daphne --fd 5 django_project.asgi:channel_layer
```

If I had to use a file descriptor, does that mean that I won't be using the unix socket anymore ? If so, what changes can I expect to my nginx config ?

Absolutely any help would be appreciated in trying to solve this.

Thanks in advance.

**Comment by andrewgodwin** [comment] 2017-10-27 19:33
I'm afraid there's not really much I can do for you - 502 errors happen due to a lot of things (machine running too slow, descriptor exhaustion, thread exhaustion, network blips, misconfiguration) and I don't know if it is a daphne-specific bug or not.

Based on the logs you've provided (about the upstream closing the connection during response) it looks like Daphne might be closing the socket early? But hard to tell.

I unfortunately can't provide free tech support for issues like this, so I'll have to close this issue - if you trace it down to something reproducible that is an error in Daphne, then I can help you with that.

**Closed by andrewgodwin** 2017-10-27 19:33 UTC

**Comment by muhammedabad** [comment] 2017-10-27 21:44
@andrewgodwin thanks for the feedback.

We have found an issue where the browser console constantly logs messages about a slow network being detected. The project is currently running on a small virtual machine behind a VPN that is used for internal testing. I'll move it over to a more production-like environment and see if the issue persists.

**Comment by Ahmadzadeh920** [comment] 2019-07-09 08:23
Hi I have failed: Error during WebSocket handshake: Unexpected response code: 404 I create daphne.sock for websocket and gunicorn.sock for http request and and in nginx.conf proxy_pass equals to unixes. but have this errors
