### ISSUE TITLE
Feature request: Forward actually used WebSocket subprotocol to websocket.*

### ISSUE THREAD

**Issue by yongthecoder** [django/daphne#139] opened 2017-09-19 14:37 UTC
A channels consumer should be able to know the actual WebSocket subprotocol that is chosen by daphne when accepting a connection in order to support multiple subprotocols with different message formats.

Please consider to add this feature. Thanks.

**Comment by andrewgodwin** [comment] 2017-09-19 17:52
Closing this as a duplicate of https://github.com/django/channels/issues/744

**Closed by andrewgodwin** 2017-09-19 17:52 UTC
