### ISSUE TITLE
Daphne sevice unit for systemd is not working, daphne.socket vs daphne.sevice

### ISSUE THREAD

**Issue by mahsa-poorjafari** [django/daphne#202] opened 2018-05-22 13:38 UTC
Hi, @andrewgodwin
I am facing a problem to start daphne service by systemd on CentOS.
The first question, I've got confused with daphne.socket and daphne.sevice. Is daphne.socket file necessary? Or I can run daphne service by having only daphne.sevice?

The second question, daphne.service is not running.
Here my daphne.socket unit which starts successfully:

```
#/etc/systemd/system/daphne.socket
[Unit]
Description=Daphne Socket

[Socket]
ListenStream=0.0.0.0:80
Accept=yes
[Install]
WantedBy=sockets.target
```

**systemctl status daphne.socket** :

> daphne.socket - Daphne Socket
>    Loaded: loaded (/etc/systemd/system/daphne.socket; enabled; vendor preset: disabled)
>    Active: active (listening) since (date) CEST; 1s ago
>    Listen: 0.0.0.0:80 (Stream)
>  Accepted: 1; Connected: 0

And here is my daphne.service unit:

 ```
#/etc/systemd/system/daphne.service
 [Unit]
 Description=daphne server script for MyProject
 Requires=daphne.socket
 After=syslog.target
 After=network.target
 After=nginx.service
 
 [Service]
 Type=simple
 WorkingDirectory=/path/to/MyProject
 ExecStart=path/to/venv/bin/daphne -b 0.0.0.0 -p 80 --root-path=/path/to/MyProject MyProject.asgi:channel_layer
 Restart=always
 StandardInput=socket
 StandardError=journal
 
 [Install]
 WantedBy=multi-user.target
```

**systemctl status daphne.service**

> daphne.service - daphne server script for MyProject
>    Loaded: loaded (/etc/systemd/system/daphne.service; enabled; vendor preset: disabled)
>    Active: failed (Result: start-limit) since (date) CEST; 3s ago
>  Main PID: 20347 (code=exited, status=1/FAILURE)

> CentOS-74-64-minimal systemd[1]: daphne.service failed to run 'start' task: Invalid argument
> CentOS-74-64-minimal systemd[1]: Failed to start daphne server script for MyProject
> CentOS-74-64-minimal systemd[1]: Unit daphne.service entered failed state.
> CentOS-74-64-minimal systemd[1]: daphne.service failed.
> CentOS-74-64-minimal systemd[1]: Starting daphne server script for MyProject...
> CentOS-74-64-minimal systemd[1]: daphne.service holdoff time over, scheduling restart.
> CentOS-74-64-minimal systemd[1]: start request repeated too quickly for daphne.service

**journalctl -u daphne.service**

> CentOS-74-64-minimal systemd[1]: Got more than one socket.

So, anyone has any idea what is wrong here? Because I don't.
Thank you so much in advance

**Comment by andrewgodwin** [comment] 2018-05-22 15:03
I'm afraid I don't know too much about systemd - maybe someone else can help. Since this is not a bug in Daphne itself, though, I will close this ticket.

**Closed by andrewgodwin** 2018-05-22 15:03 UTC

**Comment by mahsa-poorjafari** [comment] 2018-05-25 09:46
It is working right now.
I remove the daphne.socket unit and modified the daphne.service unit.
Here the daphne.service uni file:
`[Unit]
Description=daphne server script  
After=network.target

[Service]
WorkingDirectory=/path/to/myproject
Environment=DJANGO_SETTINGS_MODULE=myproject.settings
ExecStart=/path/to/myproject/env/bin/daphne -b 0.0.0.0 -p 8001 myproject.asgi:channel_layer
Restart=always

[Install]
WantedBy=multi-user.target`


And of course:
systemctl daemon-reload
systemctl restart daphne.service

**Comment by rushike** [comment] 2020-04-02 09:30
I my case to above works but, after some time , or after some request, 
Daphne stops processing the request, means i get nothing even after printing **debug logs**.

But as I do `systemctl restart daphne.service` everthing works as normal for while, 
And shuts down again.

**Comment by juandavidvallejo** [comment] 2020-06-03 14:27
> I my case to above works but, after some time , or after some request,
> Daphne stops processing the request, means i get nothing even after printing **debug logs**.
> 
> But as I do `systemctl restart daphne.service` everthing works as normal for while,
> And shuts down again.

Hi, did you found the anwer?, i can resolve

**Comment by Aashishchoudhary** [comment] 2024-07-29 03:24
yes please explain what is the answer..
