### ISSUE TITLE
took too long to shut down and was killed

### ISSUE THREAD

**Issue by sh1man999** [django/daphne#533] opened 2024-10-08 11:14 UTC
You can't fix this bug for years, it still remains in new versions.
I'm using the latest version of asgi, django 5.1.1, daphne 4.1.2.
I am constantly plagued by these errors and the server is constantly dying.
```
[WARNING][daphne.server] Application instance <Task pending name='Task-4097' coro=<ASGIApp.call() running at /var/www/vision/.venv/lib/python3.10/site-packages/engineio/async_drivers/asgi.py:74> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]>> for connection <WebRequest at 0x7f30f769a740 method=POST uri=/api/service/barrier/relay/jogging/ clientproto=HTTP/1.1> took too long to shut down and was killed.

[WARNING][daphne.server] Application instance <Task pending name='Task-538701' coro=<ASGIApp.call() running at /var/www/vision/.venv/lib/python3.10/site-packages/engineio/async_drivers/asgi.py:74> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]>> for connection <WebRequest at 0x7ff069451ba0 method=POST uri=/api/service/tickets/ clientproto=HTTP/1.1> took too long to shut down and was killed.
```

reproduce:

https://github.com/jessamynsmith/daphne_hang/blob/main/README.md

**Comment by carltongibson** [comment] 2024-10-08 11:48
The views in the example there aren't making any attempt to handle the task cancellation, or exit cleanly. 

You should probably use `async def` views for long running external calls, and then handle the cancellation as per [the Django docs on handling disconnects](https://docs.djangoproject.com/en/5.1/topics/async/#handling-disconnects).

**Comment by sh1man999** [comment] 2024-10-08 11:53
uvicorn is working great. It doesn't have that problem.

**Comment by carltongibson** [comment] 2024-10-08 11:58
Perhaps you could investigate the extra machinery it's using and make a suggestion? That would be great.

**Comment by carltongibson** [comment] 2024-10-08 14:37
I'm going to close as a duplicate of https://github.com/django/channels/issues/1119

**Closed by carltongibson** 2024-10-08 14:37 UTC

**Comment by ericmeadows** [comment] 2025-01-15 01:54
Yeah - this is not a duplicate, @carltongibson...it's a fundamental problem with Daphne.  I'm siding with @sh1man999 on this being an issue.  Also, this wasn't a problem with the 5.0 releases...
`django = "^5.0.4"` worked fine (at times) with `daphne = "^4.1.2"`, though this would come up less often.  What's crazier is this can be intermittent...I'm just surprised at this.
