### ISSUE TITLE
TypeError: object HttpResponse can't be used in 'await' expression

### ISSUE THREAD

**Issue by kojibhy** [django/daphne#343] opened 2020-11-04 07:09 UTC
when working with dev server all works good, but when i swithc to daphne server i got this issues when visiting any endpoint API/ Admin:
```python
2020-11-04 07:05:08,071 INFO     Starting server at tcp:port=8000:interface=0.0.0.0
2020-11-04 07:05:08,072 INFO     HTTP/2 support enabled
2020-11-04 07:05:08,072 INFO     Configuring endpoint tcp:port=8000:interface=0.0.0.0
2020-11-04 07:05:08,073 INFO     Listening on TCP address 0.0.0.0:8000
ERROR:django.request: Internal Server Error: /admin/login/ (2020-11-04 07:05:11; log.py:224)
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File ".../lib/python3.8/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_response(request, response)
  File ".../lib/python3.8/site-packages/django/middleware/common.py", line 106, in process_response
    if response.status_code == 404:
AttributeError: 'coroutine' object has no attribute 'status_code'
2020-11-04 07:05:12,076 ERROR    Exception inside application: object HttpResponse can't be used in 'await' expression
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/django/core/handlers/asgi.py", line 161, in __call__
    response = await self.get_response_async(request)
  File ".../lib/python3.8/site-packages/django/core/handlers/base.py", line 148, in get_response_async
    response = await self._middleware_chain(request)
TypeError: object HttpResponse can't be used in 'await' expression
127.0.0.1:41488 - - [04/Nov/2020:07:05:12] "GET /admin/login/?next=/admin/oloo/ownermodel/" 500 453
```

Django==3.1.3
asgiref==3.3.0
daphne==3.0.0
channels==3.0.0

**Comment by carltongibson** [comment] 2020-11-04 08:56
Duplicate of https://github.com/django/channels/issues/1558

@kojibhy — Thanks for the report, but can we keep to one version please? (Just noise otherwise.)

**Closed by carltongibson** 2020-11-04 08:56 UTC
